services:
  - type: web
    name: abdullah-portfolio-website
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: ADMIN_EMAILS
        value: mohommadhuafnan756@gmail.com,aamabdullah441@gmail.com
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
