services:
  - type: web
    name: abdullah-portfolio-website
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: ADMIN_EMAIL
        value: mohommadhuafnan756@gmail.com
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_EMAIL_FROM
        value: onboarding@resend.dev
      - key: SESSION_SECRET
        generateValue: true
